### ISSUE TITLE
Does not compile as of v3.2.0 of the C++ ITensor library

### ISSUE THREAD

**Issue by georgeglidden** [emstoudenmire/parity#1]
Due to a recent [breaking change](https://www.itensor.org/news/23_07_17_format.html) in ITensor, learn.cc doesn't compile due to `format` being called on line 114
```
 for(auto n : range(link)) link.at(n) = Index(2,format("Link,l=%d",n));
```
but replacing with `tinyformat::format` fixes the bug.

I also had to comment out line 205
```
Print(dist);
```
as the function was unrecognized, but that might be local to my machine.

**Comment by emstoudenmire** [comment]
Hi George, thanks for reporting this. Would you be willing to submit a pull request making this change so that the code compiles with the newest ITensor version?
